version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: local_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: localdb
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    container_name: local_mongo
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    container_name: local_redis
    ports:
      - "6379:6379"
